# Configuration for tuning of the collider
config_collider:
  config_beambeam:
    nemitt_x: 2.5e-6
    nemitt_y: 2.5e-6

# Configuration for the track job
config_simulation:
  # Collider file
  collider_file: ../collider/collider.json

  # Initial off-momentum
  delta_max: 27.e-5

  # Tracking
  n_turns: 300000 # number of turns to track

  # Beam to track
  beam: lhcb1 #lhcb1 or lhcb2

# Log
log_file: tree_maker.log
