# Configuration for tuning of the collider
config_collider:
  config_beambeam:
    nemitt_x: 2.2e-6
    nemitt_y: 2.2e-6

# Configuration for the track job
config_simulation:
  # Collider file
  collider_file: ../../../collider/collider.json

  # Dictionnary of interpolated elements
  regression_file: ../d_element_attr_regression.pkl

  # Distribution in the normalized xy space
  particle_file: ../../../../../base_collider/particles/00.parquet

  # Initial off-momentum
  delta_max: 27.e-5

  # Tracking
  n_turns: 300 # number of turns to track

  # Beam to track
  beam: lhcb1 #lhcb1 or lhcb2

# Log
log_file: tree_maker.log
