# Configuration for tuning of the collider
config_collider:
  config_beambeam:
    skip_beambeam: true
    bunch_spacing_buckets: 10
    num_slices_head_on: 11
    num_long_range_encounters_per_side:
      ip1: 25
      ip2: 0
      ip5: 25
      ip8: 0
    sigma_z: 0.09
    num_particles_per_bunch: 180000000000.0
    nemitt_x: 2.2e-6
    nemitt_y: 2.2e-6
    mask_with_filling_pattern:
      pattern_fname: /home/HPC/cdroin/dynamic_collapse/master_study/master_jobs/filling_scheme/25ns_2464b_2452_1842_1821_236bpi_12inj_hybrid_converted.json
      i_bunch_b1: 411 # If not specified, the bunch with the worst schedule is chosen
      i_bunch_b2: 410 # Same. A value for i_bunch_b1 and i_bunch_b2 must be specified if pattern_fname is specified

# Configuration for the track job
config_simulation:
  # Collider file
  collider_file: ../../../collider/collider.json

  # Dictionnary of interpolated elements
  elements_file: ../d_element_attr_regression.pkl

  # Distribution in the normalized xy space
  particle_file: ../../../../../base_collider/particles/00.parquet

  # Initial off-momentum
  delta_max: 27.e-5

  # Tracking
  n_turns: 300000 # number of turns to track

  # Beam to track
  beam: lhcb1 #lhcb1 or lhcb2

# Log
log_file: tree_maker.log
