# Collider file
collider_json: ../1_build_distr_and_collider/collider/collider.json

# Distribution in the normalized xy space
particle_file: ../particles/13.parquet

# Metric
epsn_1: 2.5e-6           # normalised emittance x
epsn_2: 2.5e-6           # normalised emittance y
delta_max: 0.00027       # initial off-momentum

# Tracking
n_turns: 1000000         # number of turns to track

# Parameters that can be scanned are added below. Each group yields a different sets of operation
# on the resulting collider (e.g. retune, recompute luminosity, etc).
parameters_scanned:
  group_1:
    on_x1:
    on_x5:
    qx: 62.305
    qy: 60.310999999999986
  group_2:
    qx:
    qy:
    dqx:
    dqy:
    i_oct_b1:
    i_oct_b2:
  group_3:
    i_bunch_nb_b1:
    i_bunch_nb_b2:

# Log
log_file: /afs/cern.ch/work/c/cdroin/private/example_DA_study/master_study/example_HL_tunescan/xtrack_0643/tree_maker.log
collider_file: ../collider/collider.json
