'root':
  setup_env_script: '/home/HPC/sterbini/2021_12_07/miniconda/bin/activate'
  generations:
    1: # Make the particle distribution
      job_folder: '../master_jobs/000_make_part_distribution'
      job_executable: 000_make_distrib.py # has to be a python file
    2: # Launch the pymask and prepare the xlines
      job_folder: '../master_jobs/001_machine_model'
      job_executable: 000_pymask.py # has to be a python file
      files_to_clone: # relative to the template folder
        - optics_specific_tools.py
        - clean_it.sh
    3: # Launch the tracking
      job_folder: '../master_jobs/002_tracking_job'
      job_executable: 000_track.py # has to be a python file
      files_to_clone: # relative to the template folder
        - clean_it.sh
  # first generation
  children:
    '000':
      test: 'test1'
      new_parameter: 'test1'
      children:
        '000':
          qx0: 62.31
          qy0: 60.32
          test: 'test'
          children:
            '000':
              particle_file: '/../../distrib_abc/000.parquet' 
              xline_json:  '../xsuite_lines/line_bb_for_tracking.json'
              n_turns: 1000
            '001':
              particle_file: '../../distrib_abc/000.parquet' 
              xline_json:  '../xsuite_lines/line_bb_for_tracking.json'
              n_turns: 2000
        '001':
          qx0: 62.313
          qy0: 60.318
          children:
            '000':
              particle_file: '../../distrib_abc/000.parquet' 
              xline_json:  '../xsuite_lines/line_bb_for_tracking.json'
              n_turns: 1e3
