# Configuration for the track job
config_simulation:
  # Collider file
  collider_file: ../../../1_build_distr_and_collider/collider/collider.json

  # Elements file
  elements_file: ../dynamic_configure.pkl

# Save collider or not
dump_collider: false
dump_config_in_collider: false

# Log
log_file: "tree_maker.log"
