# Configuration for the track job
config_simulation:
  # Elements file
  elements_file: ../dynamic_configure.pkl

# Save collider or not
dump_collider: false
dump_config_in_collider: false

# Log
log_file: tree_maker.log
